import type { Metadata } from "next";
import ReactMarkdown from "react-markdown";

export const metadata: Metadata = {
  title: "Letter from Co-Chairs",
  description:
    "A welcome message from the Co-Chairs of International Friends, Randy Spalding and Pat Gilman.",
};

const letterContent = `
Thank you for your interest in International Friends!

International Friends has been in existence since 1952, and it is one of the oldest organizations of its type in the United States. We are governed by a Board of Directors composed of international students and citizen representatives, and we work directly with the International Student Services office at the University of Arizona. Your participation in our organization, either as international students or local hosts, is greatly encouraged and very much appreciated.

Students describe International Friends as an invaluable asset for learning about American life outside of the academic environment. Hosts have equally expressed tremendous satisfaction with the rich and rewarding relationships they have developed with students that often continue for many years. The goodwill generated by these friendships frequently affects both students and hosts for the rest of their lives.

Please take the time to explore our website. For further information or questions about International Friends, you can contact us at info@ifriendstucson.org.

Join us! A new friend is waiting...

Sincerely,

**Randy Spalding and Pat Gilman**
*Co-chairs, International Friends, Inc.*
`;

export default function LetterPage() {
  return (
    <div className="pt-32 pb-20">
      <div className="container-narrow">
        <h1 className="text-4xl font-display font-bold mb-8 text-center">
          Letter from the Co-Chairs
        </h1>
        <div className="prose prose-lg max-w-none">
          <ReactMarkdown>{letterContent}</ReactMarkdown>
        </div>
      </div>
    </div>
  );
}
